chore: git hooks fix

diff --git a/.git-hooks/prepare-commit-msg b/.git-hooks/prepare-commit-msg
--- a/.git-hooks/prepare-commit-msg
+++ b/.git-hooks/prepare-commit-msg
@@ -10,34 +10,114 @@ HOOK_DISABLE_NOTICE=0 # Set to 1 to disable the notice when the hook exits with 
 # Your script begins here.
 # The last command to run, or explicit "exit" commands, will determine the status code to Git.
 
-# From: https://dev.to/craicoverflow/enforcing-conventional-commits-using-git-hooks-1o5p
-# Build the Regular Expression Options.
-types="build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test"
-scope_minlen=1
-scope_maxlen=16
-scope_regexp="[a-z0-9_.-]{${scope_minlen},${scope_maxlen}}"
-subject_minlen=4
-subject_maxlen=120
-subject_regexp="[a-z0-9_. -]{${subject_minlen},${subject_maxlen}}"
 
+# From https://github.com/craicoverflow/sailr
 
-# Build the Regular Expression String.
-regexp="^(revert: )?(${types})(\(${scope_regexp}\))?!?: ${subject_regexp}[^A-Z.,?]{1,}$"
+LIGHT_GRAY="\033[0;37m"
+YELLOW="\033[33m"
+CYAN="\033[36m"
+RED="\033[31m"
+UNDO_COLOR="\033[0m"
 
-# Validate the commit message.
-if [[ ! "$(head -1 $1)" =~ ${regexp} ]]; then
-  # Print the hook error message.
-  echo
-  echo "The commit message was not formatted correctly. Rejecting the commit request."
-  echo " - https://www.conventionalcommits.org/en/v1.0.0/"
-  echo " - https://github.com/conventional-changelog/commitlint/tree/master/%40commitlint/config-conventional"
-  echo
-  echo " Having trouble with the format? Just not sure of how to commit correctly? https://commitlint.io/"
-  echo " Something weird happening? Use https://regexr.com/ with the following expression to validate your commit."
-  echo "  - Expression: /${regexp}/"
-  echo
+release_tag=master
+sailr_repo="https://github.com/craicoverflow/sailr/tree/$release_tag"
+
+# checks that jq is usable
+check_jq_exists_and_executable() {
+if ! [ -x "$(command -v jq)" ]; then
+  echo "\`commit-msg\` hook failed. Please install jq."
   exit 1
 fi
+}
+
+# check if the config file exists
+# if it doesnt we dont need to run the hook
+check_sailr_config() {
+  if [[ ! -f "$CONFIG" ]]; then
+    echo "Sailr config file is missing. To set one see $sailr_repo#usage"
+    exit 0
+  fi
+}
+
+set_config() {
+  local_config="$PWD/sailr.json"
+
+  if [ -f "$local_config" ]; then
+    CONFIG=$local_config
+  elif [ -n "$SAILR_CONFIG" ]; then
+    CONFIG=$SAILR_CONFIG
+  fi
+}
+
+# set values from config file to variables
+set_config_values() {
+  enabled=$(jq -r .enabled "$CONFIG")
+
+  if [[ ! $enabled ]]; then
+    exit 0
+  fi
+
+  revert=$(jq -r .revert "$CONFIG")
+  types=($(jq -r '.types[]' "$CONFIG"))
+  min_length=$(jq -r .length.min "$CONFIG")
+  max_length=$(jq -r .length.max "$CONFIG")
+}
+
+# build the regex pattern based on the config file
+build_regex() {
+  set_config_values
+
+  regexp="^[.0-9]+$|"
+
+  if $revert; then
+      regexp="${regexp}^([Rr]evert|[Mm]erge):? )?.*$|^("
+  fi
+
+  for type in "${types[@]}"
+  do
+    regexp="${regexp}$type|"
+  done
+
+  regexp="${regexp%|})(\(.+\))?: "
+
+  regexp="${regexp}.{$min_length,$max_length}$"
+}
+
+print_error() {
+  echo "${RED}[Invalid Commit Message]${UNDO_COLOR}"
+  echo "------------------------"
+}
+
+set_config
+
+# check if the repo has a sailr config file
+check_sailr_config
+
+# make sure jq is installed
+check_jq_exists_and_executable
+
+# get the first line of the commit message
+INPUT_FILE=$1
+commit_message=`head -n1 $INPUT_FILE`
+
+build_regex
+
+commit_msg_len=${#commit_message}
+if [[ $commit_msg_len -lt $min_length || $commit_msg_len -gt $max_length ]]; then
+  print_error
+  echo "${LIGHT_GRAY}Expected length: Min=${CYAN}$min_length${UNDO_COLOR} Max=${CYAN}$max_length${UNDO_COLOR}"
+  echo "Actual length: ${YELLOW}${commit_msg_len}${UNDO_COLOR}"
+  exit 1
+fi
+
+if [[ ! $commit_message =~ $regexp ]]; then
+  print_error
+  echo "${LIGHT_GRAY}Expected prefixes: ${CYAN}${types[@]}${UNDO_COLOR}"
+  # echo "${LIGHT_GRAY}Expected Regex: ${CYAN}$regexp${UNDO_COLOR}"
+  echo "Actual commit message: ${YELLOW}\"$commit_message\"${UNDO_COLOR}"
+  exit 1
+fi
+
 
 # Print the hook success message.
 echo "Validated 'prepare-commit-msg' hook."
